# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOSTraning2018' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'ObjectMapper'
  pod 'AlamofireObjectMapper'

  # Pods for iOSTraning2018

  target 'iOSTraning2018Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOSTraning2018UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
